In [1]:
#inputs
# x = [[1], [2],[ 3], [2.5]]
x = [1, 2, 3, 2.5]

#weights
w = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

In [2]:
type(x)

list

In [3]:
type(w)

list

In [4]:
# y = w . x

In [5]:
import numpy as np

w= np.array(w)
w

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [6]:
w.shape

(3, 4)

In [7]:
x= np.array(x)
x

array([1. , 2. , 3. , 2.5])

In [8]:
x.shape

(4,)

In [9]:
y = np.dot (w,x)
y

array([ 2.8  , -1.79 ,  1.885])

In [10]:
xt = x.T
xt

array([1. , 2. , 3. , 2.5])

In [11]:
xt.shape

(4,)

In [12]:
wt = w.T
wt

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [13]:
wt.shape

(4, 3)

In [14]:
y = np.dot(x,wt)
y

array([ 2.8  , -1.79 ,  1.885])

In [15]:
#biases 
b = [2, 3, 0.5]
b=  np.array(b)
b

array([2. , 3. , 0.5])

In [16]:
y = y+b
y

array([4.8  , 1.21 , 2.385])

new

In [26]:
x = [1,2,3]
x = np.array(x)
x.shape

(3,)

In [27]:
x

array([1, 2, 3])

In [28]:
w = [[1,2,3,],
     [4,5,6],
     [7,8,9]]
w = np.array(w)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
w.shape

(3, 3)

In [31]:
y = np.dot(x,w)
y

array([30, 36, 42])

In [32]:
y1 = np.dot(w,x)
y1

array([14, 32, 50])