In [38]:
#inputs
# x = [[1], [2],[ 3], [2.5]]
x = [1, 2, 3, 2.5]

#weights
w = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

In [39]:
type(x)

list

In [40]:
type(w)

list

In [41]:
# y = w . x

In [42]:
import numpy as np

w= np.array(w)
w

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [43]:
w.shape

(3, 4)

In [44]:
x= np.array(x)
x

array([1. , 2. , 3. , 2.5])

In [45]:
x.shape

(4,)

In [46]:
y = np.dot (w,x)
y

array([ 2.8  , -1.79 ,  1.885])

In [47]:
xt = x.T
xt

array([1. , 2. , 3. , 2.5])

In [48]:
xt.shape

(4,)

In [49]:
wt = w.T
wt

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [50]:
wt.shape

(4, 3)

In [51]:
y = np.dot(x,wt)
y

array([ 2.8  , -1.79 ,  1.885])

In [52]:
#biases 
b = [2, 3, 0.5]
b=  np.array(b)
b

array([2. , 3. , 0.5])

In [53]:
y = y+b
y

array([4.8  , 1.21 , 2.385])