In [2]:
x = [[1, 2, 3, 2.5],
    [2., 5., -1., 2],
    [-1.5, 2.7, 3.3, -0.8]]

w1 = [[0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]

b1 = [2, 3, 0.5]

w2 = [[0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]]

b2 = [-1, 2, -0.5]

In [5]:
import numpy as np
x = np.array(x)
x

array([[ 1. ,  2. ,  3. ,  2.5],
       [ 2. ,  5. , -1. ,  2. ],
       [-1.5,  2.7,  3.3, -0.8]])

In [6]:
w1 = np.array(w1)
w1

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [8]:
b1 = np.array(w1)
w1

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [9]:
w2 = np.array(w2)
w2

array([[ 0.1 , -0.14,  0.5 ],
       [-0.5 ,  0.12, -0.33],
       [-0.44,  0.73, -0.13]])

In [10]:
b2 = np.array(b2)
b2

array([-1. ,  2. , -0.5])