In [32]:
x = [[1, 2, 3, 2.5],
    [2., 5., -1., 2],
    [-1.5, 2.7, 3.3, -0.8]]

w1 = [[0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]

b1 = [2, 3, 0.5]

w2 = [[0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]]

b2 = [-1, 2, -0.5]

In [33]:
import numpy as np
x = np.array(x)
x

array([[ 1. ,  2. ,  3. ,  2.5],
       [ 2. ,  5. , -1. ,  2. ],
       [-1.5,  2.7,  3.3, -0.8]])

In [34]:
w1 = np.array(w1)
w1

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [35]:
b1 = np.array(b1)
b1

array([2. , 3. , 0.5])

In [36]:
w2 = np.array(w2)
w2

array([[ 0.1 , -0.14,  0.5 ],
       [-0.5 ,  0.12, -0.33],
       [-0.44,  0.73, -0.13]])

In [37]:
b2 = np.array(b2)
b2

array([-1. ,  2. , -0.5])

In [38]:
z1 = np.dot(x,w1.T) 
z1

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [39]:
y1 = z1+ b1
y1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [40]:
z2 = np.dot (y1,w2.T)
z2

array([[ 1.5031 , -3.04185, -1.53875],
       [ 1.2434 , -4.7332 , -5.2633 ],
       [ 0.00686, -0.58746,  0.14345]])

In [41]:
y2=z2+b2
y2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])